  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
name: build Zephyr on QEMU

env:
  ZEPHYR_TOOLCHAIN_VARIANT: zephyr
  ZEPHYR_SDK_INSTALL_DIR: ~/zephyr-sdk-0.11.1

on:
  schedule:
    - cron:  '0 * * * *'

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: Set up Python 
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: cache-pip-linux
      uses: actions/cache@v1
      with:
        path: ~/.cache/pip
        key: ubuntu-latest-pip-3.7
        restore-keys: |
          ubuntu-latest-pip-3.7
    - name: install pytest
      run: |
        pip3 install pytest west pyelftools
    - name: install  multi-purpose west tool
      run: |
        sudo apt update
        sudo apt install --no-install-recommends git cmake ninja-build gperf
      shell: bash
    - name : install tool2
      run : sudo apt install ccache dfu-util device-tree-compiler wget
      shell: bash
    - name : install tool3
      run: sudo apt install python3-pip python3-setuptools python3-tk python3-wheel xz-utils file
      shell : bash
    - name : install tool4
      run: |
        sudo apt autoremove 
        sudo apt install --fix-missing make gcc gcc-multilib g++-multilib libsdl2-dev
      shell: bash
    - name: install cmake
      run : |
        wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null | sudo apt-key add -
        sudo apt update
        sudo apt install cmake
    - name: install west
      run: |
        pip3 install --user -U west
        echo 'export PATH=~/.local/bin:"$PATH"' >> ~/.bashrc
        source ~/.bashrc
    - name : install tool chain
      run : |
        wget https://github.com/zephyrproject-rtos/sdk-ng/releases/download/v0.11.1/zephyr-sdk-0.11.1-setup.run
        chmod +x zephyr-sdk-0.11.1-setup.run
        ./zephyr-sdk-0.11.1-setup.run -- -d ~/zephyr-sdk-0.11.1
        rm -f ./zephyr-sdk-0.11.1-setup.run
    - name : install tabulate
      run: |
        pip install tabulate
    - name:  update west
      run: |
        source ~/.bashrc
        cd ~
        west init zephyrproject
        cd zephyrproject
        west update
        cd zephyr
        echo $GITHUB_WORKSPACE
        ls $GITHUB_WORKSPACE
        git log --format="%H" -n 1 > $GITHUB_WORKSPACE/SHA_zephyr_master.txt
      shell: bash
    - name: update dependencies
      run: |
        cd ~/zephyrproject/zephyr/scripts
        pip install -r requirements.txt
    - name: free disk space
      run: |
        sudo swapoff -a
        sudo rm -f /swapfile
        sudo apt clean
        docker rmi $(docker image ls -aq)
        df -h
        date
    - name: build qemu_cortex_m0
      run: |
        cd ~/zephyrproject/zephyr
        source zephyr-env.sh
        scripts/sanitycheck  --device-testing -p qemu_cortex_m0
    - name: build qemu_cortex_m3
      run: | 
        cd ~/zephyrproject/zephyr
        source zephyr-env.sh
        scripts/sanitycheck  --device-testing -p qemu_cortex_m3
    - name: build qemu_cortex_a53
      run: |
        cd ~/zephyrproject/zephyr
        source zephyr-env.sh
        scripts/sanitycheck  --device-testing -p qemu_cortex_a53


